version: '3.1'

services:

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres_rest_api
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: phone_book
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  postgres_data:
    driver: local
