env: "local"
storage:
  driver: "postgres_driver"
  host: "localhost"
  port: 5432
  username: "username"
  password: "pass"
  database: "phone_book"
  storage_path: "internal/store/data/store.json"
  indexes_path: "internal/store/data/indexes.json"
http_server: 
 address: localhost:1234
 timeout: 3s
 idle_timeout: 60s
